language: cpp
compiler: g++
sudo: required
dist: trusty
 
addons:
  apt:
    source:
    - ppa:beineri/opt-qt593-trusty
    packages:
    - qt59base
    - qt59tools
    - libssl-dev

script:
  - source /opt/qt59/bin/qt59-env.sh
  - mkdir build
  - cd build
  - qmake ..
  - make
