language: cpp
sudo: required
dist: xenial
services:
  - docker
  
install:
  - docker pull coderus/sailfishos-platform-sdk
 
script:
  - chmod -R a+rwx .
  - docker run --volume "$PWD:/home/src1" -w /home/src1 coderus/sailfishos-platform-sdk mb2 -t SailfishOS-3.0.0.8-armv7hl build
