version: 2
jobs:
  build:
    docker:
      - image: r1tschy/sailfishos-platform-sdk:3.0.1.11
    steps:
      - checkout
      - run: mb2 -t SailfishOS-3.0.1.11-armv7hl build
      - store_artifacts:
          path: /home/nemo/project/RPMS/
          destination: rpms
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

