version: 2
jobs:
  build:
    docker:
      - image: r1tschy/sailfishos-platform-sdk:3.0.1.11
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: git config user.email "root@example.com" && git config user.name "root"
      - run: mb2 -t SailfishOS-3.0.1.11-armv7hl build -d
      - store_artifacts:
          path: /home/nemo/project/RPMS/
          destination: rpms
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

