version: 2
jobs:
  build:
    docker:
      - image: r1tschy/sailfishos-platform-sdk:3.0.1.11
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: git config user.email "circleci@nowhere.nowhere" && git config user.name "circleci"
      - run: mb2 build -d -X
      - run: mb2 -t SailfishOS-3.0.1.11-armv7hl make check
      - store_artifacts:
          path: /home/nemo/project/RPMS/
          destination: rpms
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
